### ISSUE TITLE
How can I get 'data/IMDB.mat' ?

### ISSUE THREAD

**Issue by ThePiii** [YangSJ2019/AHEAD#2]
How can I get 'data/IMDB.mat' ?

**Comment by YangSJ2019** [comment]
You can download 'IMDB.mat' in the 'data' branch of this repo.

**Comment by Crystal-LiuBojia** [comment]
Hello, this work has left a very deep impression on me, and I would like to follow your work. If possible, could you share the dataset with me? 980132844@qq.com

**Comment by YangSJ2019** [comment]
> Hello, this work has left a very deep impression on me, and I would like to follow your work. If possible, could you share the dataset with me? [980132844@qq.com](mailto:980132844@qq.com)

Hi, thanks for your interest in our work. You can download processed dataset in the 'data' branch of this repo. If you mean the raw dataset, maybe it's a little hard for me to find those raw data.

**Comment by Crystal-LiuBojia** [comment]
> > Hello, this work has left a very deep impression on me, and I would like to follow your work. If possible, could you share the dataset with me? [980132844@qq.com](mailto:980132844@qq.com)
> 
> Hi, thanks for your interest in our work. You can download processed dataset in the 'data' branch of this repo. If you mean the raw dataset, maybe it's a little hard for me to find those raw data.

Sorry, I can not find the 'data' branch of your repo. Could you please share me with the link?
![image](https://github.com/YangSJ2019/AHEAD/assets/86413062/17dad698-1aff-4c70-8b81-e11acaa99a8c)
