### ISSUE TITLE
Description of processed datasets in matlab format

### ISSUE THREAD

**Issue by ltoropova** [YangSJ2019/AHEAD#3]
Hi, I am very interested in your work and would like to adopt my own dataset to use AHEAD model. But it looks like CoAID.mat and IMDB.mat are processed versions of original datasets and it is not clear what `X1`, `X2` and `edge_index` keys in the datasets stands for. 
Are `X1` and `X2` attribute matrices for 2 types of nodes? How were they generated? 
What is `edge_index`?

**Comment by YangSJ2019** [comment]
Hi, thanks for your interest! X<sub>1</sub> and X<sub>2</sub> are attribute matrices for 2 types of nodes. It's a sub-graph of the raw graph and I rename those nodes. You can refer to raw IMDB dataset in [pytorch.geometric](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#heterogeneous-datasets).  Edge_index is the index of edges between different types of edges.

**Comment by ltoropova** [comment]
Thank you!
